// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('cs.services', []);

  angular.module('cs.directives', ['cs.services']);

  angular.module('cs', ['cs.directives']).value('cs.config', {});

}).call(this);
